---
- name: User Playbook
  become: yes
  become_method: sudo
  user: centos
  hosts: all
  tasks:
  - name: Add User Bob
    user:
      name: bob
      comment: "John Smith"
      groups: wheel
      enerate_ssh_key: yes
      state: present

  - name: Add User Lisa
    user:
      name: lisa
      state: absent
